image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay
  GOPATH: $CI_PROJECT_DIR/../gopath

stages:
  - build
  - push

before_script:
  - docker info
  - mkdir -p $GOPATH
  - apk update
  - apk add make

.build_template: &build_definition
  script:
    - make pull
    - make env
    - make $PLATFORM
  except:
    - tags

.push_template: &push_definition
  script:
    - make pull
    - make env
    - make $PLATFORM
  after_script:
    - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
    - make push
  only:
    - tags

android-arm:
  stage: build
  variables:
    PLATFORM: android-arm
  <<: *build_definition
android-arm-hub:
  stage: push
  variables:
    PLATFORM: android-arm
  <<: *push_definition

android-x64:
  stage: build
  variables:
    PLATFORM: android-x64
  <<: *build_definition
android-x64-hub:
  stage: push
  variables:
    PLATFORM: android-x64
  <<: *push_definition

android-x86:
  stage: build
  variables:
    PLATFORM: android-x86
  <<: *build_definition
android-x86-hub:
  stage: push
  variables:
    PLATFORM: android-x86
  <<: *push_definition

darwin-x64:
  stage: build
  variables:
    PLATFORM: darwin-x64
  <<: *build_definition
darwin-x64-hub:
  stage: push
  variables:
    PLATFORM: darwin-x64
  <<: *push_definition

linux-arm:
  stage: build
  variables:
    PLATFORM: linux-arm
  <<: *build_definition
linux-arm-hub:
  stage: push
  variables:
    PLATFORM: linux-arm
  <<: *push_definition

linux-armv7:
  stage: build
  variables:
    PLATFORM: linux-armv7
  <<: *build_definition
android-armv7-hub:
  stage: push
  variables:
    PLATFORM: linux-armv7
  <<: *push_definition

linux-arm64:
  stage: build
  variables:
    PLATFORM: linux-arm64
  <<: *build_definition
linux-arm64-hub:
  stage: push
  variables:
    PLATFORM: linux-arm64
  <<: *push_definition

linux-x64:
  stage: build
  variables:
    PLATFORM: linux-x64
  <<: *build_definition
linux-x64-hub:
  stage: push
  variables:
    PLATFORM: linux-x64
  <<: *push_definition

linux-x86:
  stage: build
  variables:
    PLATFORM: linux-x86
  <<: *build_definition
linux-x86-hub:
  stage: push
  variables:
    PLATFORM: linux-x86
  <<: *push_definition

windows-x64:
  stage: build
  variables:
    PLATFORM: windows-x64
  <<: *build_definition
windows-x64-hub:
  stage: push
  variables:
    PLATFORM: windows-x64
  <<: *push_definition

windows-x86:
  stage: build
  variables:
    PLATFORM: windows-x86
  <<: *build_definition
windows-x86-hub:
  stage: push
  variables:
    PLATFORM: windows-x86
  <<: *push_definition
